### ISSUE TITLE
logoda bir dona a href bo'lsa yetadi uni ichida image va imagedan keyin Ansormed degan so'zni yozib qo'ysangiz bo'lardi )

### ISSUE THREAD

**Issue by Azizbek-Kalandarov** [Ilkhomjon2604/AnsorMed#1]
![image](https://user-images.githubusercontent.com/74859443/133889413-c0eed9e3-f5bf-4d2f-a794-689cd51199f0.png)

**Comment by Ilkhomjon2604** [comment]
the issue is completed. rasm va yozuvni bitta link ichiga olindi
